### ISSUE TITLE
Advertencia de dependencia local al construir el proyecto

### ISSUE THREAD

**Issue by jorsol** [jug-ni/PICO#4]
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for jug-nicaragua:PICO:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for miglayout:net.miginfocom.swing.MigLayout:jar should not point at files within the project directory, ${project.basedir}/src/main/libs/miglayout15-swing.jar will be unresolvable by dependent projects @ line 73, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

**Comment by fjavier** [comment]
¿Porque razon se encuentra esta libreria incluida directamente en el proyecto?
Deberia manejarse como las demas o ¿se hizo alguna modificación que no se encuentra en la versión oficial.?
En caso contrario no veo el porque se incluya directamente en el proyecto como jar.
<--Versión oficial -->
<dependency>
			<groupId>com.miglayout</groupId>
			<artifactId>miglayout-swing</artifactId>
			<version>5.0</version>
		</dependency>

**Comment by berroteran** [comment]
> @fjavier  no encontre como contestarte directamente desde tu mensaje. 
Las razones son las siguientes: 
1) - No encontre esta libreria disponible en los respositorios de Maven, y no tenia tiempo para probar todo, dado que este la ofrece eclipse, me parecio la mejor opcion desde el punto de vista de funcionalidad.  Si revisas el jar, te das cuenta que la libreria dice apple, y en maven, hay varias parecidas, pero ninguna que corresponda a lo que incluya el JAR.

2) -  Dado que este es un proyecto didáctico y funcional, me pareció una buena idea mostrar como se referencia una librería de forma local, ademas de las razones del punto 1. 

Se puede manejar vía maven, perfectamente, siempre que sea probado adecuadamente, o ustedes recomienden uno en el que hayan trabajado,  el único punto a favor de dejarlo es meramente pedagógico.

Lo dejo a votación.

**Comment by jorsol** [comment]
> Se puede manejar vía maven, perfectamente, siempre que sea probado adecuadamente, o ustedes recomienden uno en el que hayan trabajado, el único punto a favor de dejarlo es meramente pedagógico.

No es una buena practica, no se deberia usar ni por aprendizaje.
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#System_Dependencies

> Important note: This is marked deprecated.

>**systemPath**: FOR SYSTEM SCOPE ONLY. Note that use of this property is discouraged and may be replaced in later versions.

La opcion 3 de este blog parece interesante:
https://brunozambiazi.wordpress.com/2016/01/09/installing-3rd-party-jars-in-maven-project/
